# Generated by Django 5.0.6 on 2024-05-18 15:57

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("currency", models.CharField(choices=[("BDT", "BDT")], max_length=5)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("exclude_from_total_balance", models.BooleanField(default=False)),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("Basic Wallet", "Basic"),
                            ("Credit Wallet", "Credit"),
                            ("Goal Wallet", "Goal"),
                            ("Investment Wallet", "Investment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_changed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet",
                "verbose_name_plural": "wallets",
                "db_table": "wallets",
                "ordering": ["-added_at"],
            },
        ),
    ]
