# Generated by Django 5.0.6 on 2024-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
