# Generated by Django 5.0.6 on 2024-05-19 14:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_alter_wallet_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_changed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction_category",
                "verbose_name_plural": "transaction_categories",
                "db_table": "transaction_categories",
                "ordering": ["-added_at"],
            },
        ),
    ]
