# Generated by Django 5.0.6 on 2024-05-19 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_transactioncategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Transaction Category",
                "verbose_name_plural": "Transaction Categories",
            },
        ),
    ]
