# Generated by Django 5.0.6 on 2024-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0005_alter_wallet_options_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="category",
            field=models.ManyToManyField(
                related_name="wallets_categories", to="wallets.transactioncategory"
            ),
        ),
    ]
