# Generated by Django 5.0.6 on 2024-05-19 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0006_wallet_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="wallet_type",
            new_name="wallet",
        ),
    ]
